server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/medsync_auth
    username: postgres
    password: Jarvis@29
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # For dev. For prod, prefer 'validate' or migrations (Flyway/Liquibase)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Remove H2 console config because we're not using H2 now

jwt:
  secret: "change-this-secret-in-prod-its-very-important"
  access-token-expiration-seconds: 1800   # 30 minutes
