services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: medsync-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: medsync-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16-alpine
    container_name: medsync-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jarvis@29
      # Default DB = "postgres"; we'll create others manually
    ports:
      - "5433:5432"
    volumes:
      - medsync-postgres-data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: medsync-auth-service
#    ports: # UNCOMMENT THEM TO EXPOSE THEM SEPARATELY
#      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medsync_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Jarvis@29
    depends_on:
      - kafka
      - postgres

  patient-service:
    build: ./patient-service
    container_name: medsync-patient-service
#    ports: # UNCOMMENT THEM TO EXPOSE THEM SEPARATELY
#      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medsync_patient
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Jarvis@29
    depends_on:
      - auth-service
      - postgres

  doctor-service:
    build: ./doctor-service
    container_name: medsync-doctor-service
#    ports: // UNCOMMENT THEM TO EXPOSE THEM SEPARATELY
#      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medsync_doctor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Jarvis@29
    depends_on:
      - auth-service
      - postgres

  appointment-service:
    build: ./appointment-service
    container_name: medsync-appointment-service
#    ports: // UNCOMMENT THEM TO EXPOSE THEM SEPARATELY
#      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medsync_appointment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Jarvis@29
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - auth-service
      - kafka
      - postgres

  notification-service:
    build: ./notification-service
    container_name: medsync-notification-service
#    ports: // UNCOMMENT THEM TO EXPOSE THEM SEPARATELY
#      - "8085:8085"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  gateway-service:
    build: ./gateway-service
    container_name: medsync-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - patient-service
      - doctor-service
      - appointment-service
      - notification-service

volumes:
  medsync-postgres-data:
