server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medsync_patient
    username: postgres      # change to your DB user
    password: Jarvis@29      # change to your DB password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

jwt:
  secret: "change-this-secret-in-prod-its-very-important"
  access-token-expiration-seconds: 3600

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG
    com.medsync.patient_service: DEBUG
    org.springframework.security: DEBUG
    com.medsync.security: DEBUG

